# Generated by Django 5.2.8 on 2026-04-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='student',
            name='curso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='student',
            name='turma',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Turma'),
        ),
    ]
