# Generated by Django 5.2.8 on 2026-04-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ativo',
        ),
        migrations.AlterField(
            model_name='user',
            name='papel',
            field=models.CharField(choices=[('operador', 'Operador'), ('empresa', 'Empresa'), ('gestor', 'Gestor'), ('fiscal', 'Fiscal'), ('admin', 'Administrador')], default='operador', max_length=20),
        ),
    ]
