# Generated by Django 5.2.8 on 2026-04-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_ativo_alter_user_papel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('serie', models.CharField(choices=[('6EF', '6º Ano EF'), ('7EF', '7º Ano EF'), ('8EF', '8º Ano EF'), ('9EF', '9º Ano EF'), ('1EM', '1º Ano EM'), ('2EM', '2º Ano EM'), ('3EM', '3º Ano EM')], max_length=3, verbose_name='Série/Ano')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='estudantes/fotos/', verbose_name='Foto do estudante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Estudante',
                'verbose_name_plural': 'Estudantes',
                'ordering': ['nome'],
            },
        ),
    ]
