# Generated by Django 6.0.4 on 2026-05-12 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_ativo_student_curso_student_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Turma')),
                ('turno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='LogLiberacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('biometrica', 'Biométrica'), ('manual', 'Manual')], max_length=20)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.student')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Liberação',
                'verbose_name_plural': 'Logs de Liberação',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudantes', to='core.turma', verbose_name='Turma'),
        ),
        migrations.CreateModel(
            name='Digital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hex', models.CharField(max_length=255, unique=True, verbose_name='Código hexadecimal')),
                ('dedo', models.CharField(blank=True, choices=[('polegar_d', 'Polegar Direito'), ('indicador_d', 'Indicador Direito'), ('medio_d', 'Médio Direito'), ('anelar_d', 'Anelar Direito'), ('minimo_d', 'Mínimo Direito'), ('polegar_e', 'Polegar Esquerdo'), ('indicador_e', 'Indicador Esquerdo'), ('medio_e', 'Médio Esquerdo'), ('anelar_e', 'Anelar Esquerdo'), ('minimo_e', 'Mínimo Esquerdo')], max_length=20, null=True, verbose_name='Dedo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitais', to='core.student')),
            ],
            options={
                'verbose_name': 'Digital',
                'verbose_name_plural': 'Digitais',
                'unique_together': {('estudante', 'dedo')},
            },
        ),
    ]
