# Generated by Django 5.2.8 on 2026-05-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_almoco_logliberacao_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='almoco',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
