# Generated by Django 6.0.4 on 2026-05-13 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_almoco_observacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Turma')),
                ('turno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='serie',
        ),
        migrations.AlterField(
            model_name='student',
            name='curso',
            field=models.CharField(blank=True, choices=[('Técnico Integrado em Eletromecânica', 'Técnico Integrado em Eletromecânica'), ('Técnico Subsequente em Eletromecânica', 'Técnico Subsequente em Eletromecânica'), ('Técnico Subsequente em Manutenção e Suporte em Informática', 'Técnico Subsequente em Manutenção e Suporte em Informática'), ('Técnico Subsequente em Modelagem do Vestuário', 'Técnico Subsequente em Modelagem do Vestuário'), ('Técnico PROEJA em Modelagem e Vestuário', 'Técnico PROEJA em Modelagem e Vestuário'), ('Bacharelado em Ciência da Computação', 'Bacharelado em Ciência da Computação'), ('Licenciatura em Computação', 'Licenciatura em Computação'), ('Licenciatura em Física', 'Licenciatura em Física'), ('Tecnológico em Automação Industrial', 'Tecnológico em Automação Industrial'), ('Tecnológico em Design de Moda', 'Tecnológico em Design de Moda'), ('FIC Libras Básico', 'FIC Libras Básico'), ('FIC Libras Intermediário', 'FIC Libras Intermediário'), ('FIC Front-End com React', 'FIC Front-End com React'), ('Qualificação Cuidadora de Idosos', 'Qualificação Cuidadora de Idosos'), ('Qualificação Recepcionista', 'Qualificação Recepcionista')], max_length=100, null=True, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='student',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudantes', to='core.turma', verbose_name='Turma'),
        ),
    ]
