# Generated by Django 5.2.8 on 2026-05-29 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_curso_turma_remove_student_serie_alter_student_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_refeicao', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor por refeição')),
                ('horario_inicio', models.TimeField(default='11:00', verbose_name='Horário de início da cantina')),
                ('horario_fim', models.TimeField(default='14:00', verbose_name='Horário de fim da cantina')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.CreateModel(
            name='LogConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=100)),
                ('valor_antigo', models.TextField(blank=True, null=True)),
                ('valor_novo', models.TextField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Configuração',
                'verbose_name_plural': 'Logs de Configuração',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('biometria', 'Problema na biometria'), ('comportamento', 'Comportamento do aluno'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='core.student')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoValidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('total_refeicoes', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('protocolo', models.CharField(editable=False, max_length=50, unique=True)),
                ('data_validacao', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('fiscal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Período Validado',
                'verbose_name_plural': 'Períodos Validados',
                'unique_together': {('data_inicio', 'data_fim')},
            },
        ),
    ]
