# Generated by Django 5.2.8 on 2026-05-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_curso_turma_remove_student_serie_alter_student_curso_and_more'),
        ('core', '0008_curso_alter_student_curso'),
    ]

    operations = [
    ]
