# Generated by Django 5.2.8 on 2026-06-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_configuracao_logconfiguracao_ocorrencia_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='almoco',
            index=models.Index(fields=['data_hora'], name='core_almoco_data_ho_69dc29_idx'),
        ),
        migrations.AddIndex(
            model_name='almoco',
            index=models.Index(fields=['estudante', 'data_hora'], name='core_almoco_estudan_7357e5_idx'),
        ),
    ]
