# Generated by Django 5.2.8 on 2026-06-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_almoco_core_almoco_data_ho_69dc29_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='almoco',
            name='data',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='almoco',
            unique_together={('estudante', 'data')},
        ),
    ]
# Generated by Django 5.2.8 on 2026-06-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_almoco_core_almoco_data_ho_69dc29_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='almoco',
            name='data',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='almoco',
            unique_together={('estudante', 'data')},
        ),
    ]
