# Generated by Django 5.2.8 on 2026-06-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_populate_data_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almoco',
            name='data',
            field=models.DateField(default='2020-01-01', editable=False),
            preserve_default=False,
        ),
    ]
