# Generated by Django 5.2.8 on 2026-06-18 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_almoco_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ativo',
            field=models.BooleanField(default=datetime.date.today, verbose_name='Ativo'),
        ),
    ]
# Generated by Django 5.2.8 on 2026-06-18 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_almoco_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ativo',
            field=models.BooleanField(default=datetime.date.today, verbose_name='Ativo'),
        ),
    ]
